---
# tasks file for arillso.localization

- name: 'windows : Set TimeZone {{ timezone_os | default(timezone_default) }}'
  win_timezone:
    timezone: '{{ timezone_os | default(timezone_default) }}'
  vars:
    timezone_os: '{{ localization_timezone_windows }}'
    timezone_default: '{{ localization_timezone }}'

- name: 'windows : Set format, location and unicode and copy settings'
  win_region:
    location: '{{ localization_region.location }}'
    format: '{{ localization_region.format }}'
    unicode_language: '{{ localization_region.unicode_language }}'
    copy_settings: true

- name: 'windows : Sets the language list for the current user account'
  win_shell: 'Set-WinUserLanguageList de-CH -Force'

- name: 'windows : Sets the default input method override for the user account'
  win_shell: "{{ command + ' ' + localization_inputlang }}"
  vars:
    command: 'Set-WinDefaultInputMethodOverride -InputTip'

- name: 'windows : Loggin Keyboard Language'
  win_regedit:
    path: "HKLM:\\ANSIBLE\\Keyboard Layout\\Preload"
    name: '1'
    data: '{{ localization_keyboardlang }}'
    type: 'String'
    hive: C:\Users\Default\NTUSER.dat
